### ISSUE TITLE
Morning session

### ISSUE THREAD

**Issue by balerum03** [jessicafarias/Personal_bot#1]
You are doing an amazing job so far congratulations for all the hard work you have put into this project.
Here are some things you can improve to make your project even better:
- Make a little guide on the console for users to know what to do next after the run your code on the console.
- If you think you can do it, make the bot work on the console to see and immediate result. (avoid going to telegram)
Remember these are things that are not necessary but we think they would make your project look super cool.

**Comment by jessicafarias** [comment]
I have implemented what you suggest, thanks a lot @balerum03 .
